### ISSUE TITLE
Reading and writing motor current values

### ISSUE THREAD

**Issue by orhanyor** [gitcnd/VescUartLite#1]
Great work! i was wondering if it is possible to read and write motor current max and motor current max brake values to set them so we can avoid connecting the vesc to the computer.

**Comment by gitcnd** [comment]
I do not remember what settings can be applied over the UART - if those are possible, then yes - this code can do that.  You'd need to find out what the command and data bytes are to set what you want though.

**Comment by orhanyor** [comment]
i was looking at the code but sadly its not commented hard to figure out what command does what. probably just connecting to the computer is easier way :) thanks anyway

**Comment by gitcnd** [comment]
Yeah - this code just makes use of the VESC API's - you'd need to look to the VESC doc the lists of commands and parameters they expect etc.
