### ISSUE TITLE
Can not get it to work. No data received.

### ISSUE THREAD

**Issue by IHateNameStealers** [gitcnd/VescUartLite#2]
Hi Chris and the rest of the world,

I've done some vesc Arduino projects before (using SolidGeek his VescUart), but would love to use yours as I would like to get the watt_hours value directly from the VESC.

Whatever I try, I can not get any value from the VESC using your library and provided example (VescUartLite_example.ino).

Just to make sure I'm doing it correct.

Using a Nano. 
TX from VESC to RX on Nano.
RX from VESC to TX on Nano.
GND to GND

I've enabled and set the UART baudrate in the VESC to 250000
No data is being received on the Nano :(

Am I missing something here?
Any help will be appreciated.

Thank you.

**Comment by gitcnd** [comment]
They changed the protocol and now send more data than a standard Arduino can buffer without some serious code refactoring.  You'll probably need to find a more modern lib to drive your VESC these days.

**Comment by IHateNameStealers** [comment]
That's to bad.
Thank you for the info.
